version: '3.2'
services:
  zero:
    image: 'dgraph/dgraph:${dgraphVersion}'
    volumes:
      - type: volume
        source: dgraph
        target: /dgraph
        volume:
          nocopy: true
    network_mode: host
    # ports:
    #   - '${zeroPort}:${zeroPort}'
    #   - '6080:6080'
    restart: on-failure
    command: 'dgraph zero --bindall=$bindall --my=${addrHost}:${zeroPort}'
  alpha:
    image: 'dgraph/dgraph:${dgraphVersion}'
    depends_on:
      - zero
    volumes:
      - '$LocalPath/service:/dgraph/service'
      - type: volume
        source: dgraph
        target: /dgraph
        volume:
          nocopy: true
    network_mode: host
    # ports:
    #   - 8080:8080
    #   - 7080:7080
    #   - 9080:9080
    tty: true
    restart: on-failure
    command: 'bash ./service/bulk-it-or-not-bulk-it.sh'
  ratel:
    image: 'dgraph/ratel:latest'
    volumes:
      - type: volume
        source: dgraph
        target: /dgraph
        volume:
          nocopy: true
    network_mode: host
    # ports:
    #   - 8000:8000
    command: dgraph-ratel
volumes:
  dgraph:
    driver: local
